added an option to choose the movie type you are searching by and als…
Lukada-taiya/Frenzy pull request #9
Opened 2024-07-23 09:08 UTC by ChiragShukla222

2024-07-23 21:45 UTC, Lukada-taiya commented on src/App.css
> +.container {
This class styling overrides the previous container styling. It is not needed, please remove it

2024-07-23 23:40 UTC, Lukada-taiya requested changes
The styling you provided overrides the previous styling and markup of the app. Please take my corrections into consideration before it can be merged

2024-07-23 23:40 UTC, Lukada-taiya commented on src/App.css
> +@media (min-width: 600px) {
change the media query to min-width: 799px. To match with previous styles

2024-07-23 23:40 UTC, Lukada-taiya commented on src/App.css
> +form {
Add 
>justify-content: start 

to this flex styling

2024-07-23 23:40 UTC, Lukada-taiya commented on src/App.css
> +.container {
This container class styling overrides the previous container styling. It is not needed, please remove it

2024-07-23 23:40 UTC, Lukada-taiya commented on package-lock.json
The styling you provided overrides the previous styling and markup of the app. Please take my corrections into consideration before it can be merged

2024-07-24 10:28 UTC, ChiragShukla222 commented on package-lock.json
Thank you for your feedback and for pointing out the necessary corrections. I appreciate your attention to detail and have carefully reviewed your suggestions. I’m pleased to inform you that all your corrections have been taken into consideration and I'm working on it .

2024-07-24 17:53 UTC, ChiragShukla222 commented
Hi, Lukada I've made all the changes that you suggested, please review it and merge the PR.

2024-07-25 18:18 UTC, Lukada-taiya approved these changes
That is some nice work. There are still some styling issues I discovered but I will add it as a new issue.

2024-07-25 18:18 UTC, merged